# Generated by Django 3.1.3 on 2021-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='credit_amount',
            field=models.CharField(default=3, max_length=1),
        ),
    ]
