version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/datacollector
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gekyume
      - POSTGRES_DB=datacollector
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    container_name: rabbitmq
  front:
    build:
      context: ../dcfront
      dockerfile: Dockerfile
    container_name: front
    command: yarn serve --host 0.0.0.0 --port 8001
    volumes:
      - ../dcfront/src:/dcfront/src
    ports:
      - 8001:8001
    depends_on:
      - web


volumes:
  postgres_data:
