# Generated by Django 3.1.2 on 2020-11-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201109_1108'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
    ]
