# Generated by Django 3.1.2 on 2020-11-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201109_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='staff',
        ),
    ]
