# Generated by Django 3.1.2 on 2020-11-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201109_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
    ]
