# Generated by Django 3.1.2 on 2020-11-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_teacher_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kbtu_mail',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('FIT', 'Faculty of Information Technologies'), ('FGGE', 'Faculty of Geology and Geological Exploration'), ('FEOGI', 'Faculty of Energy and Oil and Gas Industry'), ('FGE', 'Faculty of General Education'), ('BS', 'Business School'), ('ISE', 'International School of Economics'), ('KMA', 'Kazakhstan Maritime Academy'), ('SMC', 'School of Mathematics and Cybernetics'), ('SCE', 'School of Chemical Engineering')], max_length=50, null=True)),
                ('degree', models.CharField(blank=True, choices=[('Laboratory assistant', 'Laboratory assistant'), ('Senior laboratory assistant', 'Senior laboratory assistant'), ('Assistant', 'Assistant'), ('Lecturer', 'Lecturer'), ('Senior Lecturer', 'Senior Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
