# Generated by Django 3.1.3 on 2020-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
