# Generated by Django 3.1.3 on 2021-01-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20201114_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('FIT', 'Faculty of Information Technologies'), ('Faculty of Geology and Geological Exploration', 'Faculty of Geology and Geological Exploration'), ('FEOGI', 'Faculty of Energy and Oil and Gas Industry'), ('FGE', 'Faculty of General Education'), ('BS', 'Business School'), ('ISE', 'International School of Economics'), ('KMA', 'Kazakhstan Maritime Academy'), ('SMC', 'School of Mathematics and Cybernetics'), ('SCE', 'School of Chemical Engineering')], max_length=50, null=True),
        ),
    ]
