# Generated by Django 3.1.3 on 2021-01-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210113_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../files/files/image/avatars/profile_image.img', null=True, upload_to='files/images/avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Faculty of Information Technologies', 'Faculty of Information Technologies'), ('Faculty of Geology and Geological Exploration', 'Faculty of Geology and Geological Exploration'), ('Faculty of Energy and Oil and Gas Industry', 'Faculty of Energy and Oil and Gas Industry'), ('Faculty of General Education', 'Faculty of General Education'), ('Business School', 'Business School'), ('International School of Economics', 'International School of Economics'), ('Kazakhstan Maritime Academy', 'Kazakhstan Maritime Academy'), ('School of Mathematics and Cybernetics', 'School of Mathematics and Cybernetics'), ('School of Chemical Engineering', 'School of Chemical Engineering')], max_length=50, null=True),
        ),
    ]
