# Generated by Django 3.1.3 on 2021-01-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210114_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='files/images/avatars/profile_image.jpg', null=True, upload_to='files/images/avatars'),
        ),
    ]
